### ISSUE TITLE
La tabla aplicaciones debe tener los campos git que ahora están en instapp

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/instrumentacion#5]
Los 3 campos git_ (con su contenido actual) van a la tabla aplicaciones.

La pk es 'aplicacion'

**Comment by estefi-capece** [comment]
Debería tener otros campos?

**Comment by emilioplatzer** [comment]
Sí, version y bp_version (o se la versión conocida del producto y la versión de backend-plus que conoce). Esos dos campos también hay que agregarlos a instapp (que son la versión instalada del producto y la versión de backend plus).
